In [1]:
import numpy as np

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [10]:
from sklearn.tree import DecisionTreeClassifier

In [3]:
from sklearn.datasets import load_iris

iris = load_iris()

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.3)

In [6]:
from sklearn.model_selection import cross_val_score

In [11]:
scores1 = cross_val_score(LogisticRegression(max_iter = 10000), X_train, y_train)
scores1

array([0.9047619 , 0.95238095, 0.95238095, 1.        , 0.95238095])

In [12]:
scores2 = cross_val_score(SVC(max_iter = 10000), X_train, y_train)
scores2

array([0.9047619 , 0.95238095, 0.95238095, 0.95238095, 0.95238095])

In [13]:
scores3 = cross_val_score(RandomForestClassifier(), X_train, y_train)
scores3

array([0.9047619 , 0.9047619 , 0.95238095, 0.9047619 , 0.95238095])

In [14]:
scores4 = cross_val_score(DecisionTreeClassifier(), X_train, y_train)
scores4

array([0.9047619 , 0.85714286, 0.95238095, 0.9047619 , 0.9047619 ])

###  THE BEST ALGORITHIM

In [15]:
np.average(scores1)

0.9523809523809523

In [16]:
np.average(scores2)

0.9428571428571428

In [17]:
np.average(scores3)

0.9238095238095237

In [18]:
np.average(scores4)

0.9047619047619048