In [2]:
import numpy as np 

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [3]:
from sklearn.datasets import load_digits
digits = load_digits()

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

In [9]:
lr = LogisticRegression(max_iter = 10000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9555555555555556

In [10]:
svc = SVC(max_iter = 10000)
svc.fit(X_train, y_train)
svc.score(X_test, y_test)

0.9833333333333333

In [11]:
forest = RandomForestClassifier()
forest.fit(X_train, y_train)
forest.score(X_test, y_test)

0.9648148148148148

In [12]:
from sklearn.model_selection import KFold
kf = KFold()
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [13]:
for train_index, test_index in kf.split([1, 2, 3, 4, 5, 6, 7, 8, 9]):
    print(train_index, test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [14]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [15]:
get_score(LogisticRegression(max_iter = 10000), X_train, X_test, y_train, y_test) 

0.9555555555555556

In [16]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold()
folds

StratifiedKFold(n_splits=5, random_state=None, shuffle=False)

In [18]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(max_iter = 10000, solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))
    
    

In [19]:
scores_l

[0.9222222222222223,
 0.8833333333333333,
 0.9526462395543176,
 0.958217270194986,
 0.8941504178272981]

In [20]:
scores_rf

[0.9361111111111111,
 0.9138888888888889,
 0.9665738161559888,
 0.9665738161559888,
 0.9331476323119777]

In [21]:
scores_svm

[0.9611111111111111,
 0.9444444444444444,
 0.9832869080779945,
 0.9888579387186629,
 0.9387186629526463]

In [22]:
from sklearn.model_selection import cross_val_score

In [30]:
scores1 = cross_val_score(LogisticRegression(max_iter = 10000), digits.data, digits.target)
scores1

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [31]:
scores2 = cross_val_score(SVC(max_iter = 10000), digits.data, digits.target)
scores2

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [32]:
scores3 = cross_val_score(RandomForestClassifier(), digits.data,digits.target )
scores3

array([0.93611111, 0.91666667, 0.95821727, 0.9637883 , 0.93593315])

In [33]:
np.average(scores1)

0.9143160012380068

In [34]:
np.average(scores2)

0.9632838130609718

In [35]:
np.average(scores3)

0.942143299288146